language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - build-essential
    - gawk
    - ccache
    - genromfs
    - libc6-i386
    - python-pip
    - python-dev
    - zlib1g-dev
    - gcc-4.9
    - g++-4.9
    - cmake
    - cmake-data
cache:
  ccache: true
  directories:
  - $HOME/opt
before_install:
- Tools/scripts/configure-ci.sh
script:
- pushd ..
- git clone https://github.com/3drobotics/PX4Firmware-solo.git
- mv ./PX4Firmware-solo ./PX4Firmware
- git clone https://github.com/3drobotics/PX4NuttX.git
- popd
- . ~/.profile
- pushd ArduCopter
- make configure
- make px4-v2
before_cache:
- ccache -z
compiler:
- gcc
notifications:
  email:
    on_success: always
    on_failure: always

 
